apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-driver-controller-observability-config
  namespace: {{ .Release.Namespace }}
  labels:
    extensions.gardener.cloud/configuration: monitoring
data:
  dashboard_operators: |
    csi-driver-controller-dashboard.json: |-
{{- .Files.Get "csi-driver-controller-dashboard.json" | nindent 6 }}

  dashboard_users: |
    csi-driver-controller-dashboard.json: |-
{{- .Files.Get "csi-driver-controller-dashboard.json" | nindent 6 }}

  observedComponents: |
    observedPods:
    - podPrefix: csi-driver-controller
      isExposedToUser: true

  scrape_config: |
    - job_name: csi-driver-controller
      scheme: http
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: [ shoot--max-test--flat-conf ]
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
        action: keep
        regex: csi-driver-controller-metrics;metrics
      # common metrics
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [ __meta_kubernetes_pod_name ]
        target_label: pod
      metric_relabel_configs:
      - source_labels: [ __name__ ]
        regex: ^(rest_client_requests_total|process_max_fds|process_open_fds)$
        action: keep
